### ISSUE TITLE
Actively Being Maintained?

### ISSUE THREAD

**Issue by omniacode** [angelleye/gravity-forms-braintree#18]
Hello -

Was curious to know if this is still currently being maintained as we're looking for an add-on for Braintree that can handle both One-time Payments and Recurring Payments (Subscriptions).

**Comment by angelleye** [comment]
@omniacode I'm sorry for the delay getting back to you.  Contrary to how you may feel with this delayed reply, we are indeed maintaining this plugin.

In fact, we made another update to it a few months ago that allows you to map any custom fields you have created in Gravity Forms to matching fields in Braintree.  This allows you to pass any custom data you want to Braintree so that it will be available in Braintree reports.

We don't have anything built specifically into this for subscriptions, but we could certainly do that.  We haven't had much demand for it, so priority would be an issue.

If you want to submit a feature request to our help desk at www.angelleye.com/support that would be great, and then we can discuss options for getting this done sooner rather than later.

Thanks!
