### ISSUE TITLE
Error - Gravity Forms Not Installed

### ISSUE THREAD

**Issue by apoonawa** [angelleye/gravity-forms-braintree#32]
When I activate the Gravity Forms Braintree plugin, I get an error saying this plugin has been deactivated because Gravity Forms is not available.
However, I do have the latest version of Gravity forms and its activated.
Can you help debug the problem?

**Comment by drewangell** [comment]
Hey, sorry, our GitHub issue comments were getting neglected because we primarily use Jira now.  I'm fixing that problem so these won't get stranded anymore.  

We have released an update recently that adds support for the latest version of GF.  Please apply our update and let me know if you continue to have problems.  thanks!
