### ISSUE TITLE
Issue Processing ACH Charges

### ISSUE THREAD

**Issue by timnolte** [angelleye/gravity-forms-braintree#34]
When attempting to process an ACH transaction, either with the Payment Methods selector or the standalone ACH field, clicking on the Submit button results in a "Please wait..." initial state and then there is never any response returned.

WordPress 5.8.1
Gravity Forms 2.5.10.1
Gravity Forms Braintree Payments 4.0.2
PHP 7.4

**Comment by drewangell** [comment]
Hey, sorry, our GitHub issues have been neglected a bit because we primarily use Jira.  I'm fixing that problem so we'll see these going forward.

We just released an update recently that makes everything compatible with the latest version of GravityForms.  Please apply the latest version and let me know if you continue to have any problems.  Thanks!
