### ISSUE TITLE
Are You Illegally Tracking Uses of This Plugin And Capturing Transaction Data?

### ISSUE THREAD

**Issue by timnolte** [angelleye/gravity-forms-braintree#36]
I'd like to know why it is that it appears that you are capturing transaction details being handled by this plugin and sending metrics off to some outside source. This is not disclosed and while there is apparently some opt-in option it is not and option that is configurable from the Plugin settings.

https://github.com/angelleye/gravity-forms-braintree/blob/533250017ad51e97a0e5c8e218d507162f95309f/lib/angelleye-gravity-forms-payment-logger.php#L18

**Comment by drewangell** [comment]
Hey guys, sorry I never replied here before.  We use Jira and our GitHub repo was getting a bit neglected with reguard to issues/comments.  Fixing that problem now.

The plugin does have an opt-in to share identifable information.  The logger will send info about the transaction amount and which specific PayPal gateway was used to process it, and then it will include identifiable info (ie. site_url) only if you have opted in.

This is simply so that we can provide volume data to PayPal and continue getting support in order to maintin the free plugin.

Hopefully that clarifies things.  Let me know if you have any other questions about that.
